name: 'deploy-render'
description: 'Deploy application on Render'
inputs:
  app_name:
    required: false
  app_env:
    required: false
  app_hostname:
    required: false
  branch:
    required: false
  deploy_root:
    required: false
  deploy_tags:
    required: false
outputs:
  url:
    description: 'URL where application has been deployed'
    value: ${{ steps.deploy.outputs.url }}
runs:
  using: composite
  steps:
    - name: Deploy
      shell: bash
      id: deploy
      env:
        RENDER_TOKEN: ${{ env.RENDER_TOKEN }}
        RENDER_SERVICE_ID: ${{ env.RENDER_SERVICE_ID }}
      run: |
        source platform/src/scripts/deploy-render.sh

        service=$(curl -s --request GET \
          --url "https://api.render.com/v1/services/$RENDER_SERVICE_ID" \
          --header "Authorization: Bearer $RENDER_TOKEN")

        service_url=$(echo "$service" | jq -r '.serviceDetails.url')

        echo "##[set-output name=url;]$(echo $service_url)"
